# Generated by Django 5.1.3 on 2024-12-03 18:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Payment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BillingAddrees',
            new_name='BillingAddress',
        ),
    ]
